// Imported necessary libraries for functionality
// NOTE: Ensure these imports are included at the beginning of the file

/**
 * PassengerWindow class to manage passenger registration
 * and store passenger information.
 */
import java.io.*;
import java.time.*;
import java.time.format.*;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author safwa
 */
public class PassengerWindow extends javax.swing.JFrame {
    
  // Instance of Passenger class for managing passenger details
    public Passenger p = new Passenger();
    /**
     * Creates new form BookWindow
     */
    
    
    
      /**
     * Creates new form PassengerWindow
     * Initializes GUI components
     */
    public PassengerWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     // Rest of your code follows...

    // Methods for GUI components and event handling

    /**
     * Handles actions performed on the Submit button
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        genderLabel = new java.awt.Label();
        dobLabel = new java.awt.Label();
        nameLabel = new java.awt.Label();
        addressLabel = new java.awt.Label();
        yearLabel = new java.awt.Label();
        dayLabel = new java.awt.Label();
        monthLabel = new java.awt.Label();
        addressField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        numberField = new javax.swing.JTextField();
        dayBox = new javax.swing.JComboBox<>();
        monthBox = new javax.swing.JComboBox<>();
        yearBox = new javax.swing.JComboBox<>();
        nidLabel = new java.awt.Label();
        nidField = new javax.swing.JTextField();
        passportLabel = new java.awt.Label();
        passportField = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        numberLabel = new java.awt.Label();
        maleButton = new javax.swing.JRadioButton();
        femaleButton = new javax.swing.JRadioButton();
        otherButton = new javax.swing.JRadioButton();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("passengerWindow"); // NOI18N
        setPreferredSize(new java.awt.Dimension(960, 540));
        getContentPane().setLayout(null);

        genderLabel.setAlignment(java.awt.Label.CENTER);
        genderLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        genderLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        genderLabel.setText("Gender");
        getContentPane().add(genderLabel);
        genderLabel.setBounds(290, 130, 130, 30);

        dobLabel.setAlignment(java.awt.Label.CENTER);
        dobLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dobLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        dobLabel.setText("Date of Birth");
        getContentPane().add(dobLabel);
        dobLabel.setBounds(290, 350, 130, 30);

        nameLabel.setAlignment(java.awt.Label.CENTER);
        nameLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nameLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        nameLabel.setText("Full Name");
        getContentPane().add(nameLabel);
        nameLabel.setBounds(290, 90, 130, 30);

        addressLabel.setAlignment(java.awt.Label.CENTER);
        addressLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addressLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        addressLabel.setName(""); // NOI18N
        addressLabel.setText("Permanent Address");
        getContentPane().add(addressLabel);
        addressLabel.setBounds(290, 290, 130, 30);

        yearLabel.setAlignment(java.awt.Label.CENTER);
        yearLabel.setText("YYYY");
        getContentPane().add(yearLabel);
        yearLabel.setBounds(570, 330, 80, 20);

        dayLabel.setAlignment(java.awt.Label.CENTER);
        dayLabel.setText("DD");
        getContentPane().add(dayLabel);
        dayLabel.setBounds(430, 330, 60, 20);

        monthLabel.setAlignment(java.awt.Label.CENTER);
        monthLabel.setText("MM");
        getContentPane().add(monthLabel);
        monthLabel.setBounds(500, 330, 60, 20);

        addressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFieldActionPerformed(evt);
            }
        });
        getContentPane().add(addressField);
        addressField.setBounds(430, 290, 220, 30);

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nameField);
        nameField.setBounds(430, 90, 220, 30);

        numberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberFieldActionPerformed(evt);
            }
        });
        getContentPane().add(numberField);
        numberField.setBounds(430, 170, 220, 30);

        dayBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(dayBox);
        dayBox.setBounds(430, 350, 60, 30);

        monthBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(monthBox);
        monthBox.setBounds(500, 350, 60, 30);

        yearBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004" }));
        yearBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearBoxActionPerformed(evt);
            }
        });
        getContentPane().add(yearBox);
        yearBox.setBounds(570, 350, 80, 30);

        nidLabel.setAlignment(java.awt.Label.CENTER);
        nidLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nidLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        nidLabel.setText("NID");
        getContentPane().add(nidLabel);
        nidLabel.setBounds(290, 210, 130, 30);

        nidField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nidFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nidField);
        nidField.setBounds(430, 210, 220, 30);

        passportLabel.setAlignment(java.awt.Label.CENTER);
        passportLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        passportLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        passportLabel.setText("Passport Number");
        getContentPane().add(passportLabel);
        passportLabel.setBounds(290, 250, 130, 30);

        passportField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passportFieldActionPerformed(evt);
            }
        });
        getContentPane().add(passportField);
        passportField.setBounds(430, 250, 220, 30);

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Passenger Registration");
        title.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(title);
        title.setBounds(20, 20, 920, 50);

        numberLabel.setAlignment(java.awt.Label.CENTER);
        numberLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        numberLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        numberLabel.setText("Phone Number");
        getContentPane().add(numberLabel);
        numberLabel.setBounds(290, 170, 130, 30);

        genderGroup.add(maleButton);
        maleButton.setText("Male");
        maleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(maleButton);
        maleButton.setBounds(430, 130, 60, 30);

        genderGroup.add(femaleButton);
        femaleButton.setText("Female");
        femaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(femaleButton);
        femaleButton.setBounds(510, 130, 80, 30);

        genderGroup.add(otherButton);
        otherButton.setText("Other");
        otherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherButtonActionPerformed(evt);
            }
        });
        getContentPane().add(otherButton);
        otherButton.setBounds(600, 130, 80, 30);

        submitButton.setBackground(new java.awt.Color(0, 0, 204));
        submitButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitButtonMouseClicked(evt);
            }
        });
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton);
        submitButton.setBounds(410, 400, 130, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberFieldActionPerformed
        // TODO add your handling code here:
        numberField.setText(" ");
    }//GEN-LAST:event_numberFieldActionPerformed

    private void yearBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearBoxActionPerformed

    private void femaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleButtonActionPerformed
        // TODO add your handling code here:
        femaleButton.setActionCommand("Female");
        
    }//GEN-LAST:event_femaleButtonActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
        nameField.setText(" ");
    }//GEN-LAST:event_nameFieldActionPerformed

    private void maleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleButtonActionPerformed
        // TODO add your handling code here:
        maleButton.setActionCommand("Male");
        
    }//GEN-LAST:event_maleButtonActionPerformed

    private void otherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherButtonActionPerformed
        // TODO add your handling code here:
        otherButton.setActionCommand("Other");
    }//GEN-LAST:event_otherButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        // Processing passenger details for registration

        // Boolean flag to track exceptions
        boolean exception = true;
        try {
            p.setFullName(nameField.getText());
            p.setPassportNumber(passportField.getText());
            p.setGender(genderGroup.getSelection().getActionCommand());
            p.setAddress(addressField.getText());
            p.setNID(nidField.getText());
            p.setPhoneNumber(numberField.getText());
            // Parsing date of birth and setting it in LocalDate format
            String dob = yearBox.getSelectedItem().toString() + "-" + monthBox.getSelectedItem().toString() + "-" + dayBox.getSelectedItem().toString();
            p.setDateOfBirth(LocalDate.parse(yearBox.getSelectedItem().toString() + "-" + monthBox.getSelectedItem().toString() + "-" + dayBox.getSelectedItem().toString()));
            exception = false;
        } catch (NullPointerException ex) {
            // Handling NullPointerException and resetting fields
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
            resetFields();
        } catch (PhoneNumberException ex) {
            // Handling PhoneNumberException
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
            numberField.setText("");
        } catch (NIDException ex) {
            // Handling NIDException
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
            nidField.setText("");
        } catch (PassportException ex) {
            // Handling PassportException
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
            passportField.setText("");
        } catch (DateTimeParseException ex) {
            // Handling DateTimeParseException and resetting date fields
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
            yearBox.setSelectedIndex(0);
            monthBox.setSelectedIndex(0);
            dayBox.setSelectedIndex(0);
        }
        // Check if there were no exceptions and display success message
        if (exception == false) {
            JOptionPane.showMessageDialog(null, "Passenger Registered Successfully!", "Success!", JOptionPane.PLAIN_MESSAGE);
            p.appendInfo();
            // Closing current window and opening a new window (BookWindow)
            this.dispose();
        }

    }//GEN-LAST:event_submitButtonActionPerformed

    private void addressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFieldActionPerformed
        // TODO add your handling code here:
        addressField.setText(" ");
    }//GEN-LAST:event_addressFieldActionPerformed

    private void submitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonMouseClicked

    }//GEN-LAST:event_submitButtonMouseClicked

    private void nidFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nidFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nidFieldActionPerformed

    private void passportFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passportFieldActionPerformed
        // TODO add your handling code here:
        passportField.setText(" ");
    }//GEN-LAST:event_passportFieldActionPerformed
   // Resetting all form fields
    public void resetFields() {
        nameField.setText(" ");
        passportField.setText(" ");
        genderGroup.clearSelection();
        addressField.setText(" ");
        nidField.setText(" ");
        numberField.setText(" ");
        yearBox.setSelectedIndex(0);
        monthBox.setSelectedIndex(0);
        dayBox.setSelectedIndex(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassengerWindow().setVisible(true);
            }
        });
        
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private java.awt.Label addressLabel;
    private javax.swing.JComboBox<String> dayBox;
    private java.awt.Label dayLabel;
    private java.awt.Label dobLabel;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.ButtonGroup genderGroup;
    private java.awt.Label genderLabel;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JComboBox<String> monthBox;
    private java.awt.Label monthLabel;
    private javax.swing.JTextField nameField;
    private java.awt.Label nameLabel;
    private javax.swing.JTextField nidField;
    private java.awt.Label nidLabel;
    private javax.swing.JTextField numberField;
    private java.awt.Label numberLabel;
    private javax.swing.JRadioButton otherButton;
    private javax.swing.JTextField passportField;
    private java.awt.Label passportLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel title;
    private javax.swing.JComboBox<String> yearBox;
    private java.awt.Label yearLabel;
    // End of variables declaration//GEN-END:variables
}
